{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:24:15.030Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:24:20.037Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:24:25.047Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:24:30.061Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:24:35.057Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:24:40.069Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:24:45.073Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:24:50.082Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:24:55.089Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:00.095Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:05.105Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:10.110Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:15.121Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:20.128Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:25.131Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:30.138Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:35.144Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:40.152Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:45.161Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:50.162Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:25:55.168Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:00.177Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:05.175Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:10.184Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:15.191Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:20.195Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:25.202Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:30.211Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:35.214Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:40.221Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:45.229Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:50.236Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:26:55.241Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:00.247Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:05.254Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:10.260Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:15.265Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:20.271Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:25.280Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:30.286Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:35.288Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:40.291Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:45.299Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:50.308Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:27:55.315Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:00.322Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:05.330Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:10.329Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:15.335Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:20.341Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:25.348Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:30.354Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:35.363Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:40.368Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:45.376Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:50.381Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:28:55.384Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:00.391Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:05.399Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:10.403Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:15.410Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:20.417Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:25.424Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:30.432Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:35.434Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:40.441Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:45.450Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:50.457Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:29:55.459Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:00.462Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:05.472Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:10.477Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:15.485Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:20.486Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:25.497Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:30.500Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:35.508Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:40.514Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:45.522Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:50.530Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:30:55.536Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:31:00.546Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:31:05.552Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:31:30.881Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:31:35.888Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:31:40.889Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:05.438Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:10.445Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:15.453Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:20.461Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:25.465Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:30.469Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:35.473Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:40.487Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:45.493Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:50.499Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:32:55.510Z"}
{"code":"28P01","file":"auth.c","length":101,"level":"error","line":"334","message":"Scheduled sensor data collection error: password authentication failed for user \"admin\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"admin\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:462:28)","timestamp":"2025-10-15T10:33:00.510Z"}
{"code":"ENOTFOUND","errno":-3008,"hostname":"postgres","level":"error","message":"Scheduled sensor data collection error: getaddrinfo ENOTFOUND postgres","stack":"Error: getaddrinfo ENOTFOUND postgres\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:464:28)","syscall":"getaddrinfo","timestamp":"2025-10-15T11:00:45.632Z"}
{"code":"ENOTFOUND","errno":-3008,"hostname":"postgres","level":"error","message":"Scheduled sensor data collection error: getaddrinfo ENOTFOUND postgres","stack":"Error: getaddrinfo ENOTFOUND postgres\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:464:28)","syscall":"getaddrinfo","timestamp":"2025-10-15T11:00:50.541Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:33:40.160Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:33:45.174Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:33:50.181Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:00.163Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:05.166Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:10.176Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:15.181Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:20.189Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:25.195Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:30.199Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:35.207Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:40.206Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:45.217Z"}
{"code":"42P01","file":"parse_relation.c","length":107,"level":"error","line":"1392","message":"Scheduled sensor data collection error: relation \"machines\" does not exist","name":"error","position":"16","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"machines\" does not exist\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Task._execution (/app/server.js:465:28)","timestamp":"2025-10-15T11:34:50.224Z"}
